#--------------------------------------------------------------------
#Define ALL debian packaging function
#--------------------------------------------------------------------
#To install needed components to be able to build vzgot
#sudo apt install dpkg-dev build-essential devscripts 
#vzgot dependency
#sudo apt install libcap-dev
DEBHOME = $(realpath ..)
DEBARCH	= `dpkg --print-architecture`

dodeb	: 
	  @ echo "==> Building Debian package for vzgot..."
	  @ dpkg-buildpackage -b -uc -us
	  @ echo "================================================================="
	  @ echo "  Debian package creation successful!"
	  @ echo "  Absolut path : $(APKHOME)"
	  @ echo ""
	  @ echo "  To install VZGOT (systemd) :"
	  @ echo "    sudo dpkg -i  $(DEBHOME)/$(APPNAME)_$(VERSION)_$(DEBARCH).deb \\"
	  @ echo "		$(DEBHOME)/$(APPNAME)-systemd_$(VERSION)_all.deb"
	  @ echo ""
	  @ echo "  To install VZGOT (OpenRC) :"
	  @ echo "    sudo dpkg -i  $(DEBHOME)/$(APPNAME)_$(VERSION)_$(DEBARCH).deb \\"
	  @ echo "		$(DEBHOME)/$(APPNAME)-openrc_$(VERSION)_all.deb"
	  @ echo ""
	  @ echo "  To install VZGOT (SysV init) :"
	  @ echo "    sudo dpkg -i  $(DEBHOME)/$(APPNAME)_$(VERSION)_$(DEBARCH).deb \\"
	  @ echo "		$(DEBHOME)/$(APPNAME)-sysv_$(VERSION)_all.deb"
	  @ echo "================================================================"
	  @ dh_clean

debcheck:
	  @ #lintian -L ">=error" ../*.changes
	  @ lintian -v -i -I -E --pedantic  ../*.changes
