#--------------------------------------------------------------------
#Define ALL RPM function
#--------------------------------------------------------------------
APLR	=  $(APPNAME)-$(VERSION)
#--------------------------------------------------------------------
dovzgot	:  dorpm
	   @echo "======================================================================"
	   @echo " RPM BUILD SUCCESSFUL"
	   @echo "======================================================================"
	   @echo " Your packages are available in:"
	   @echo "    $(RPMDIR)/RPMS/{$$(uname -m),noarch}/"
	   @echo ""
	   @echo " To install vzgot, choose the package matching your init system:"
	   @echo ""
	   @echo " 1) systemd-based systems (Fedora, RHEL, Rocky, openSUSE):"
	   @echo -e "sudo dnf install						\\"
	   @echo -e "  $(RPMDIR)/RPMS/noarch/vzgot-systemd-$(VERSION)*.rpm \\"
	   @echo -e "  $(RPMDIR)/RPMS/$$(uname -m)/vzgot-$(VERSION)-*.rpm"
	   @echo ""
	   @echo " 2) SysVinit-based system (Osukiss, etc.):"
	   @echo "    sudo zypper install					\\"
	   @echo "    $(RPMDIR)/RPMS/noarch/vzgot-sysv-$(VERSION)*.rpm		\\"
	   @echo "    $(RPMDIR)/RPMS/$$(uname -m)/vzgot-$(VERSION)-*.rpm"
	   @echo ""
	   @echo " Note: Using 'dnf' (or zypper) is recommended to automatically"
	   @echo "       resolve missing dependencies."
	   @echo "======================================================================"

dorpm	:  srcrpm
	   @ echo "Building RPM"
	   @ rpmbuild						\
		--quiet						\
		--define "_topdir $(RPMDIR)"			\
		--rebuild					\
		$(RPMDIR)/SRPMS/$(APPNAME)-$(VERSION)*.src.rpm
	   @ echo "Build completed"

srcrpm	:  vztar
	   @ echo "Making RPM src"
	   @ rm -fr 						\
		$(RPMDIR)/SOURCES				\
		$(APPNAME)*.src.rpm
	   @ mkdir -p $(RPMDIR)/SOURCES
	   @ mv $(APLR).tar.gz $(RPMDIR)/SOURCES
	   @ rpmbuild						\
		--quiet						\
		--define "_topdir $(RPMDIR)"			\
		-bs						\
		$(APPNAME).spec 
	   @ echo "RPM src completed"

cleanbld:
	   @ rm -fr $(RPMDIR)/*

#--------------------------------------------------------------------
RPMDIR	=	$(CURDIR)/rpmbuild
#====================================================================
