#--------------------------------------------------------------------
#Define ALL RPM function
#--------------------------------------------------------------------
RPMVER	= $(VERSION).$(DIST_ID)-$(RELEASE).$(DIST)

#--------------------------------------------------------------------
fedora									\
opensuse-tumbleweed							\
osukiss									\
	:  rpmpack rpmstore rpminfo


rpmpack	:  srcrpm
	   @ echo "Packaging $(APPNAME) for '$(DIST_ID)' distribution..."
	   @ echo ""
	   @ rpmbuild						\
		--quiet						\
		--define "_topdir $(RPMDIR)"			\
		--define "dist .$(DIST)"			\
		--rebuild					\
		$(RPMDIR)/SRPMS/$(APPNAME)-$(VERSION)*.src.rpm
	   @ echo "Build completed"

rpminfo	:
	  @ echo "================================================================="
	  @ echo "  rpm package creation successful!"
	  @ echo ""
	  @ echo "  To install VZGOT (systemd) :"
	  @ echo "    sudo rpm -Uhv  $(LOCREPO)/$(APPNAME)-$(RPMVER).$$(uname -m).rpm \\"
	  @ echo "		$(LOCREPO)/$(APPNAME)-systemd_$(RPMVER).noarch.rpm"
	  @ echo ""
	  @ echo "  To install VZGOT (SysV init) :"
	  @ echo "    sudo rpm -Uhv  $(LOCREPO)/$(APPNAME)-$(RPMVER).$$(uname -m).rpm \\"
	  @ echo "		$(LOCREPO)/$(APPNAME)-sysv-$(RPMVER).noarch.rpm"
	  @ echo "================================================================"

rpmstore:
	  @ rm -fr  $(LOCREPO)
	  @ mkdir -p $(LOCREPO)
	  @ mv 							\
		  $(RPMDIR)/RPMS/noarch/vzgot*$(VERSION)*	\
		  $(RPMDIR)/RPMS/$$(uname -m)/vzgot-$(VERSION)*	\
		  $(LOCREPO)
	  @ (							\
	    cd $(LOCREPO);					\
	    for file in *;					\
	      do						\
	      if [ -f "$$file" ]; then				\
		case "$$file" in 				\
		  *"$(DIST_ID)"*	)			\
		    ;;						\
		  *"$(VERSION)"*	)			\
		    newfile=$$(echo "$$file" |			\
		     sed "s/$(VERSION)/$(VERSION).$(DIST_ID)/");\
		    mv "$$file" "$$newfile"			\
		    ;;						\
		  esac;						\
		fi;						\
	      done;						\
	      )

srcrpm	:  vztar
	   @ echo "Making RPM src"
	   @ rm -fr 						\
		$(RPMDIR)/SOURCES				\
		$(APPNAME)*.src.rpm
	   @ mkdir -p $(RPMDIR)/SOURCES
	   @ mv $(APLR).tar.gz $(RPMDIR)/SOURCES
	   @ rpmbuild						\
		--quiet						\
		--define "_topdir $(RPMDIR)"			\
		-bs						\
		packagers/rpm/spec 
	   @ echo "RPM src completed"

cleanbld:
	   @ rm -fr $(RPMDIR)/*

#--------------------------------------------------------------------
RPMDIR	=	$(CURDIR)/rpmbuild
#====================================================================
