#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    if systemctl is-active --quiet NetworkManager; then
        systemctl reload NetworkManager.service || true
        systemctl restart NetworkManager.service || true
    fi
    systemctl daemon-reload >/dev/null || true
    systemctl enable vzgot.service >/dev/null || true
    systemctl restart vzgot.service >/dev/null || true
fi

#DEBHELPER#
exit 0
